global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'task-tracker-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/metrics'
  
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']